# Generated by Django 5.2.7 on 2025-10-21 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_test_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
