# Generated by Django 5.2.7 on 2025-10-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female',
            name='female_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='male',
            name='male_name',
            field=models.CharField(max_length=20),
        ),
    ]
