# Generated by Django 5.2.7 on 2025-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_female_female_name_alter_male_male_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='female',
            name='female_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='male',
            name='male_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='female',
            name='female_name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='male',
            name='male_name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
