# Generated by Django 5.2.7 on 2025-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(to='pages.student')),
            ],
        ),
    ]
